### ISSUE TITLE
WMD too slow!

### ISSUE THREAD

**Issue by a7u7a** [OllieFord/DS4D-Trade-Agreement-Project#1]
Help! My code takes forever to run
Document similarity measurement takes too long. At this pace it will be ready by February

**Comment by OllieFord** [comment]
You should change the model you're using! Use a smaller one - it will speed things up.

**Comment by a7u7a** [comment]
replaced the 'GoogleNews-vectors-negative300' with 'glove-wiki-gigaword-300'. 1.5gb vs 300mb.
Now times are manageable.. wonder how much will the accuracy change now.
we can always switch to the larger model for the conference poster. 
If we get in, that is
